spring:
  application:
    name: springjwt # properties?? yml? ??? ??

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver # PostgreSQL ???? ???

  jpa:
    hibernate:
      ddl-auto: update # ?? ???? ???? ???? ??/??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL ?? ??
    show-sql: true # ???? SQL ?? ?? ??


logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: ${JWT_SECRET}